name: catalog CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: npm ci
      - name: Build
        run: npm run build

  test:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: npm run lint
      - name: Test
        run: echo Running smoke test

  security-scan:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SAST (WARNING)
        run: npm audit --audit-level=high

  deploy:
    needs:
      - test
      - security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
<<<<<<< HEAD
        run: echo "Manual deploy: utilisez le bouton Deploy/Sync de l extension VS Code."
=======
        run: echo "Manual deploy"
>>>>>>> 8097074799369da5c819a9f92948789a957b7912
